name: n8n CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: n8n-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: CI
    timeout-minutes: 20
    env:
      POSTGRES_ACCOUNT_USER: admin
      POSTGRES_ACCOUNT_PASSWORD: ${{ secrets.CI_POSTGRES_PASSWORD }}
      POSTGRES_ACCOUNT_PORT: 5432
      POSTGRES_ACCOUNT_HOST: db
      POSTGRES_ACCOUNT_DATABASE: test
      POSTGRES_DB: test
      WORKFLOWS_PATH: workflows
      CREDS_PATH: credentials
      OPENROUTER_ACCOUNT_APIKEY: ${{ secrets.OPENROUTER_API_KEY }}
      ENV: DEV
      BASE_URL: http://localhost:5678
      DATABASE_URL: postgresql://admin:${{ secrets.CI_POSTGRES_PASSWORD }}@db:5432/test?schema=users

    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: ${{ secrets.CI_POSTGRES_PASSWORD }}
          POSTGRES_DB: n8n
        options: >-
          --name="db"
          --health-cmd="pg_isready -U admin -d n8n"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

      n8n:
        image: n8nio/n8n:1.107.3
        env:
          DB_TYPE: postgresdb
          DB_POSTGRESDB_HOST: db
          DB_POSTGRESDB_PORT: 5432
          DB_POSTGRESDB_DATABASE: n8n
          DB_POSTGRESDB_USER: admin
          DB_POSTGRESDB_PASSWORD: ${{ secrets.CI_POSTGRES_PASSWORD }}
          DB_POSTGRESDB_SCHEMA: n8n
          N8N_BASIC_AUTH_ACTIVE: 'false'
          N8N_HOST: 0.0.0.0
          N8N_PORT: 5678
          N8N_PROTOCOL: http
        options: >-
          --name="n8n"
          -v ${{ github.workspace }}:/workspace
          --health-cmd="(wget -q -T 5 -O - http://localhost:5678/healthz 2>/dev/null | grep -qF '{\"status\":\"ok\"}') || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (n8n workspace)
        run: npm ci

      - name: Install dependencies (n8n-workflow-tester)
        run: npm ci --prefix n8n-workflow-tester

      - name: Generate .env from template
        run: envsubst < .env > .env.patched && mv .env.patched .env

      - name: Patch credentials with env values
        run: |
          if ls credentials/*.json >/dev/null 2>&1; then
            for f in credentials/*.json; do
              tmp="$f.tmp"
              envsubst < "$f" > "$tmp"
              mv "$tmp" "$f"
            done
          fi

      - name: Run Prisma migrations
        run: |
          docker exec -u root n8n sh -lc '
            set -euo pipefail
            cd /workspace
            [ -f .env ] && set -a && . ./.env && set +a
            npx prisma migrate deploy
            npx prisma generate
          '

      - name: Import credentials via n8n CLI
        run: docker exec -u root n8n n8n import:credentials --separate --input /workspace/credentials

      - name: Import workflows via n8n CLI
        run: docker exec -u root n8n n8n import:workflow --separate --input /workspace/workflows

      - name: Run Jest tests inside n8n container
        run: |
          docker exec -u root n8n sh -lc '
            set -e
            [ -f /workspace/.env ] && set -a && . /workspace/.env && set +a
            cd /workspace
            npm test
          '

      - name: Show n8n logs on failure
        if: failure()
        run: docker logs n8n
